### ISSUE TITLE
Custom rendering of results for indiechat to include link to day page

### ISSUE THREAD

**Issue by dougbeal** [cweiske/phinde#32]
It would be very useful to be able to jump to the line on the day page.

Right now the time link looks like `https://chat.indieweb.org/dev/2017-05-24/1495641830720000`
But if it was transformed to `https://chat.indieweb.org/dev/2017-05-24#t1495641830720000`, you could jump to that line on the day page and read context.

It doesn't seem to be completely reliable, so both links would probably be required.

**Comment by cweiske** [comment]
The non-reliability issue is https://github.com/indieweb/chat.indieweb.org/issues/9
I've opened https://github.com/indieweb/chat.indieweb.org/issues/36 for the context issue.

I won't adjust phinde because that'd be a feature that cannot be used for normal website search.
